OBJS := start.o mem.o main.o  dev/dev.o  lib/lib.o net/net.o


CFLAGS := -fno-builtin -I$(shell pwd)/include 
export CFLAGS

newbin : 210.bin mktools
	gcc -o mktools mktools.c
	./mktools 210.bin new.bin	
	
	arm-linux-objdump -D -S 210.elf >dump.dis


210.bin : 210.elf
	arm-linux-objcopy -O binary 210.elf 210.bin
	
210.elf : $(OBJS)
	arm-linux-ld -Tlink.lds -o 210.elf $^
	
%.o : %.S
	arm-linux-gcc -g -c $<
	
%.o : %.c
	arm-linux-gcc ${CFLAGS} -c $<
	
lib/lib.o : 
	make -C lib all
	
dev/dev.o :
	make -C dev all
	
net/net.o :
	make -C net all
	

clean:
	rm *.o *.elf *.bin  mktools 
	make -C lib clean
	make -C dev clean
	make -C net clean
